version: '3'

services:
  gateway:
    container_name: gateway
    restart: always
    build: ./gateway
    ports:
      - '3000:3000'

  characters:
    container_name: characters
    restart: always
    build: ./characters
    ports:
      - '3001:3001'

  films:
    container_name: films
    restart: always
    build: ./films
    ports:
      - '3002:3002'

  planets:
    container_name: planets
    restart: always
    build: ./planets
    ports:
      - '3003:3003'

  database:
    container_name: database
    restart: always
    build: ./database
    ports:
      - '4000:4000'
